import os
import sys

import psycopg2 as dbapi2


INIT_STATEMENTS = [
    """CREATE TABLE PEOPLE (
    P_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(120),
    PHOTO VARCHAR(120)
)""",
    """CREATE TABLE IF NOT EXISTS FACULTIES (
    FAC_ID SERIAL PRIMARY KEY,
    FAC_NAME VARCHAR(100) NOT NULL,
    FAC_CODE VARCHAR(5) UNIQUE NOT NULL,
    BUILDING_CODE VARCHAR(5) NOT NULL
)""",
    """CREATE TABLE IF NOT EXISTS ASSISTANTS (
    AS_ID SERIAL PRIMARY KEY,
    PERSON INTEGER UNIQUE NOT NULL,
    DEPARTMENT VARCHAR(100) NOT NULL,
    LAB VARCHAR(100),
    LECTURE INTEGER,
    FOREIGN KEY PERSON REFERENCES PEOPLE(P_ID),
    FOREIGN KEY LECTURE REFERENCES LECTURES(LEC_ID),
    FOREIGN KEY LAB REFERENCES LABS(LAB_ID)
)""",
    """CREATE TABLE IF NOT EXISTS LABS (
    LAB_ID SERIAL PRIMARY KEY,
    LAB_NAME VARCHAR(100) UNIQUE,
    DEPARTMENT VARCHAR(100),
    CLUBS VARCHAR(100),
    FACULTY INTEGER,
    BUILDING  INTEGER,
    ROOM INTEGER,
    FOREIGN KEY BUILDING REFERENCES BUILDINGS(BUILD_ID),
    FOREIGN KEY ACADEMIC REFERENCES ACADEMICS(AC_ID),
    FOREIGN KEY FACULTY REFERENCES FACULTIES(FAC_ID)
)""",
    """CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    DEP_ID SERIAL PRIMARY KEY,
    DEP_NAME VARCHAR(100),
    FACULTY INTEGER,
    BUILDING INTEGER,
    FOREIGN KEY BUILDING REFERENCES BUILDINGS(BUILD_ID),
    FOREIGN KEY FACULTY REFERENCES FACULTIES(FAC_ID)
)""",
    """CREATE TABLE IF NOT EXISTS LESSONS (
    LESSON_ID SERIAL PRIMARY KEY,
    CAP INTEGER,
    ENROLLED INTEGER,
    DATE INTEGER,
    CRN INTEGER UNIQUE NOT NULL,
    CODE VARCHAR(5),
    INSTRUCTOR INTEGER,
    LOCATION INTEGER, 
    ASSISTANT INTEGER,
    CREDIT INTEGER,
    FOREIGN KEY INSTRUCTOR REFERENCES INSTRUCTORS(INS_ID),
    FOREIGN KEY ASSISTANT REFERENCES ASSISTANTS(AS_ID),
    FOREIGN KEY LOCATION REFERENCES CLASSES(CL_ID)
    )""",

    "INSERT INTO FACULTIES VALUES ('Computer and Informatics Engineering Faculty', 'BBF', 'EEB')",
]


def initialize(url):
    try:
        with dbapi2.connect(url) as connection:
            cursor = connection.cursor()
            for statement in INIT_STATEMENTS:
                cursor.execute(statement)
            cursor.close()
    except Exception as err:
        print("Error: ", err)


if __name__ == "__main__":
    url = os.getenv("DATABASE_URL")
    if url is None:
        print("Usage: DATABASE_URL=url python dbinit.py", file=sys.stderr)
        sys.exit(1)
    initialize(url)
